spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/demo/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/demo
        registration:
          spring-with-test-scope:
            provider: keycloak
            client-id: spring-with-test-scope
            client-secret: tLmZ6qe4LR40701ul7PHQnajJEwJLa8L
            authorization-grant-type: authorization_code
            scope: openid

  cloud:
    gateway:
      routes:
        - id : rs_route
          uri: lb://recipients-service
          predicates:
            - Path=/recipients-service/**
          filters:
              - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka