spring:
  application:
    name: recipients-service
server:
    port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}