spring:
  application:
    name: task-resolver-service
  kafka:
    bootstrap-servers: localhost:9092
#    consumer:
#      properties:
#        spring.json.trusted.packages: "*"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
      hibernate:
        ddl-auto: update
server:
  port: 0
recipients-service:
  url: http://recipients-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
kafka:
  backoff:
#    initial_interval: 29628 #mills
#    max_elapsed_time: 21600000 #
    initial_interval: 1000
    max_elapsed_time: 28000
    multiplier: 3

#    6*60*60*1000 = 21 600 000
#    7 200 000
#    2 400 000
#    8 00 000
#    266 666
#    88 888
#    29 629