spring:
  application:
    name: task-resolver-service
  kafka:
    bootstrap-servers: localhost:9092
#    consumer:
#      properties:
#        spring.json.trusted.packages: "*"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
server:
  port: 0
recipients-service:
  url: http://recipients-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}